# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pERmvgIKsIAnKNMc9NTJfRkVAJbqLjk0
"""

class Student:
    def __init__(self):
        self.name = "Rahul"
        self.roll = 101
        self.marks = 87.5


s1 = Student()

print("Name:", s1.name)
print("Roll:", s1.roll)
print("Marks:", format(s1.marks, ".1f"))